name: main

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main

      - name: Cache Virtual Environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/*.TAG') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Cache MyPy Cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('**/*.TAG') }}
          restore-keys: |
            ${{ runner.os }}-mypy-

      - name: Cache Ruff Cache
        uses: actions/cache@v4
        with:
          path: .ruff_cache
          key: ${{ runner.os }}-ruff-${{ hashFiles('**/*.TAG') }}
          restore-keys: |
            ${{ runner.os }}-ruff-

      - name: Install Dependencies
        run: rye sync

      - name: Run Ruff Linter
        run: rye run ruff .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main

      - name: Cache Pytest Cache
        uses: actions/cache@v2
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-pytest-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pytest-

      - name: Cache Virtual Environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/*.TAG') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install Dependencies
        run: rye sync

      - name: Run Pytest
        run: rye run pytest .
